/**
 * PM Documents Plugin
 *
 * Generates PMI-aligned project management artifacts as structured Markdown.
 * Eight tools cover the full artifact lifecycle from initiation through closeout.
 *
 * Depends on: executive.pm-knowledge (for ontology grounding)
 * Output path: configurable via outputPath (default: ./pm-artifacts)
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { PluginModule, PluginAPI } from "../../../src/plugin/types.js";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function timestamp(): string {
  return new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";
}

function headerBlock(title: string, projectName: string, date: string): string {
  return [
    `# ${title}`,
    `**Project:** ${projectName}`,
    `**Generated:** ${date}`,
    `**Framework:** PMI PMBOK-Aligned`,
    "",
  ].join("\n");
}

function saveArtifact(outputPath: string, fileName: string, content: string): string {
  try {
    mkdirSync(outputPath, { recursive: true });
    const filePath = join(outputPath, fileName);
    writeFileSync(filePath, content, "utf-8");
    return filePath;
  } catch {
    return "(file save failed — output returned inline)";
  }
}

// ─── Template Functions ───────────────────────────────────────────────────────

function buildProjectCharter(params: {
  projectName: string;
  sponsor: string;
  objectives: string[];
  scope: string;
  budget?: string;
  timeline?: string;
  stakeholders?: string[];
}): string {
  const date = timestamp();
  const lines: string[] = [
    headerBlock("Project Charter", params.projectName, date),
    "## Purpose",
    "This Project Charter formally authorizes the project and provides the Project Manager with authority to apply organizational resources to project activities.",
    "",
    "## Project Objectives",
    ...params.objectives.map((o, i) => `${i + 1}. ${o}`),
    "",
    "## Project Scope",
    params.scope,
    "",
    "## In-Scope",
    "_Define the boundaries of what this project will deliver._",
    "",
    "## Out of Scope",
    "_Define what is explicitly excluded to manage scope expectations._",
    "",
  ];

  if (params.budget) {
    lines.push("## Budget Authorization", params.budget, "");
  }

  if (params.timeline) {
    lines.push("## High-Level Timeline", params.timeline, "");
  }

  if (params.stakeholders && params.stakeholders.length > 0) {
    lines.push(
      "## Key Stakeholders",
      "| Name / Role | Responsibility |",
      "|-------------|----------------|",
      ...params.stakeholders.map((s) => `| ${s} | _To be defined_ |`),
      ""
    );
  }

  lines.push(
    "## Project Sponsor Authorization",
    `**Sponsor:** ${params.sponsor}`,
    "",
    "| Role | Name | Signature | Date |",
    "|------|------|-----------|------|",
    `| Project Sponsor | ${params.sponsor} | | |`,
    "| Project Manager | | | |",
    "",
    "## Assumptions and Constraints",
    "| Type | Description |",
    "|------|-------------|",
    "| Assumption | _List key assumptions_ |",
    "| Constraint | _List constraints (budget, schedule, resources)_ |",
    "",
    "---",
    "_Generated by Lliam PM Documents — PMI PMBOK-Aligned_"
  );

  return lines.join("\n");
}

function buildRiskRegister(params: {
  projectName: string;
  risks: Array<{
    description: string;
    category: string;
    probability: string;
    impact: string;
  }>;
}): string {
  const date = timestamp();
  const lines: string[] = [
    headerBlock("Risk Register", params.projectName, date),
    "## Risk Log",
    "",
    "| ID | Description | Category | Probability | Impact | Risk Score | Status | Owner | Response Strategy |",
    "|----|-------------|----------|-------------|--------|------------|--------|-------|-------------------|",
  ];

  params.risks.forEach((risk, i) => {
    const id = `R-${String(i + 1).padStart(3, "0")}`;
    lines.push(
      `| ${id} | ${risk.description} | ${risk.category} | ${risk.probability} | ${risk.impact} | _TBD_ | Open | _Unassigned_ | _TBD_ |`
    );
  });

  lines.push(
    "",
    "## Risk Summary",
    `- **Total Risks Identified:** ${params.risks.length}`,
    "- **High Risk:** _To be scored_",
    "- **Medium Risk:** _To be scored_",
    "- **Low Risk:** _To be scored_",
    "",
    "## Risk Management Approach",
    "Risks are monitored on a weekly basis during project status meetings. Threshold for escalation: Risk Score ≥ 15 (on a 25-point scale).",
    "",
    "---",
    "_Generated by Lliam PM Documents — PMI PMBOK-Aligned_"
  );

  return lines.join("\n");
}

function buildRaciMatrix(params: {
  projectName: string;
  workPackages: string[];
  roles: string[];
  assignments: Record<string, Record<string, string>>;
}): string {
  const date = timestamp();

  const header = ["| Work Package |", ...params.roles.map((r) => ` ${r} |`)].join("") ;
  const separator = ["| --- |", ...params.roles.map(() => " --- |")].join("");

  const rows = params.workPackages.map((wp) => {
    const cells = params.roles.map((role) => {
      const assignment = params.assignments[wp]?.[role] ?? "";
      return ` ${assignment || " "} |`;
    });
    return `| ${wp} |` + cells.join("");
  });

  return [
    headerBlock("RACI Matrix", params.projectName, date),
    "## Responsibility Assignment Matrix",
    "",
    "**Legend:** R = Responsible | A = Accountable | C = Consulted | I = Informed",
    "",
    header,
    separator,
    ...rows,
    "",
    "## Notes",
    "- Each work package must have exactly one **A** (Accountable) role",
    "- Multiple **R** (Responsible) roles are permitted",
    "- **C** (Consulted) parties provide input but do not perform the work",
    "- **I** (Informed) parties are notified of outcomes only",
    "",
    "---",
    "_Generated by Lliam PM Documents — PMI PMBOK-Aligned_",
  ].join("\n");
}

function buildStakeholderEngagementPlan(params: {
  projectName: string;
  stakeholders: Array<{
    name: string;
    role: string;
    engagementLevel: string;
    interests: string;
    strategy: string;
  }>;
}): string {
  const date = timestamp();
  const lines: string[] = [
    headerBlock("Stakeholder Engagement Plan", params.projectName, date),
    "## Purpose",
    "Define strategies to effectively engage stakeholders throughout the project lifecycle, ensuring appropriate levels of participation and support.",
    "",
    "## Stakeholder Register",
    "",
    "| Name | Role | Current Engagement | Desired Engagement | Key Interests | Engagement Strategy |",
    "|------|------|-------------------|-------------------|---------------|---------------------|",
  ];

  for (const s of params.stakeholders) {
    lines.push(
      `| ${s.name} | ${s.role} | ${s.engagementLevel} | _Target_ | ${s.interests} | ${s.strategy} |`
    );
  }

  lines.push(
    "",
    "## Engagement Level Definitions (PMI)",
    "| Level | Description |",
    "|-------|-------------|",
    "| Unaware | Unaware of project and its impact |",
    "| Resistant | Aware but resistant to change |",
    "| Neutral | Aware but neither supportive nor resistant |",
    "| Supportive | Aware and supportive of change |",
    "| Leading | Actively engaged in ensuring project success |",
    "",
    "## Communication Cadence",
    "| Audience | Method | Frequency | Owner |",
    "|----------|--------|-----------|-------|",
    "| Executive Sponsors | Status Report + Meeting | Monthly | PM |",
    "| Core Team | Stand-up / Sprint Review | Weekly | PM |",
    "| Stakeholders | Newsletter / Dashboard | Bi-weekly | PM |",
    "",
    "---",
    "_Generated by Lliam PM Documents — PMI PMBOK-Aligned_"
  );

  return lines.join("\n");
}

function buildStatusReport(params: {
  projectName: string;
  reportingPeriod: string;
  accomplishments: string[];
  plannedWork: string[];
  issues: string[];
  risks: string[];
  scheduleVariance?: string;
  budgetVariance?: string;
}): string {
  const date = timestamp();
  const lines: string[] = [
    headerBlock("Project Status Report", params.projectName, date),
    `**Reporting Period:** ${params.reportingPeriod}`,
    "",
    "## Overall Project Health",
    "| Dimension | Status | Trend |",
    "|-----------|--------|-------|",
    `| Schedule | ${params.scheduleVariance ? (params.scheduleVariance.startsWith("-") ? "🔴 Behind" : "🟢 On Track") : "🟡 TBD"} | ${params.scheduleVariance ?? "—"} |`,
    `| Budget | ${params.budgetVariance ? (params.budgetVariance.startsWith("-") ? "🔴 Over" : "🟢 On Track") : "🟡 TBD"} | ${params.budgetVariance ?? "—"} |`,
    "| Scope | 🟢 Controlled | — |",
    "| Quality | 🟢 On Track | — |",
    "",
    "## Accomplishments This Period",
    ...params.accomplishments.map((a) => `- ${a}`),
    "",
    "## Planned Work Next Period",
    ...params.plannedWork.map((p) => `- ${p}`),
    "",
  ];

  if (params.issues.length > 0) {
    lines.push(
      "## Issues",
      "| # | Description | Owner | Target Resolution |",
      "|---|-------------|-------|-------------------|",
      ...params.issues.map((issue, i) => `| ${i + 1} | ${issue} | _TBD_ | _TBD_ |`),
      ""
    );
  }

  if (params.risks.length > 0) {
    lines.push(
      "## Active Risks",
      "| # | Description | Mitigation Status |",
      "|---|-------------|-------------------|",
      ...params.risks.map((risk, i) => `| ${i + 1} | ${risk} | Active |`),
      ""
    );
  }

  lines.push(
    "---",
    "_Generated by Lliam PM Documents — PMI PMBOK-Aligned_"
  );

  return lines.join("\n");
}

function buildWbsDictionary(params: {
  projectName: string;
  workPackages: Array<{
    id: string;
    name: string;
    description: string;
    deliverables: string[];
    acceptanceCriteria: string[];
    responsibleParty: string;
  }>;
}): string {
  const date = timestamp();
  const lines: string[] = [
    headerBlock("WBS Dictionary", params.projectName, date),
    "## Purpose",
    "The WBS Dictionary provides detailed information about each component in the Work Breakdown Structure, ensuring shared understanding of deliverable scope and acceptance criteria.",
    "",
  ];

  for (const wp of params.workPackages) {
    lines.push(
      `## ${wp.id} — ${wp.name}`,
      "",
      `**Responsible Party:** ${wp.responsibleParty}`,
      "",
      "**Description**",
      wp.description,
      "",
      "**Deliverables**",
      ...wp.deliverables.map((d) => `- ${d}`),
      "",
      "**Acceptance Criteria**",
      ...wp.acceptanceCriteria.map((c) => `- ${c}`),
      "",
      "| Attribute | Value |",
      "|-----------|-------|",
      "| WBS ID | " + wp.id + " |",
      "| Status | Planned |",
      "| Start Date | _TBD_ |",
      "| End Date | _TBD_ |",
      "| Estimated Effort | _TBD_ |",
      ""
    );
  }

  lines.push(
    "---",
    "_Generated by Lliam PM Documents — PMI PMBOK-Aligned_"
  );

  return lines.join("\n");
}

function buildLessonsLearned(params: {
  projectName: string;
  phase: string;
  lessonsLearned: Array<{
    category: string;
    description: string;
    recommendation: string;
    impact: string;
  }>;
}): string {
  const date = timestamp();
  const positiveCount = params.lessonsLearned.filter((l) => l.impact === "positive").length;
  const negativeCount = params.lessonsLearned.filter((l) => l.impact === "negative").length;
  const neutralCount = params.lessonsLearned.filter((l) => l.impact === "neutral").length;

  const lines: string[] = [
    headerBlock("Lessons Learned Register", params.projectName, date),
    `**Project Phase:** ${params.phase}`,
    "",
    "## Summary",
    `- **Total Lessons:** ${params.lessonsLearned.length}`,
    `- **Positive:** ${positiveCount} | **Negative:** ${negativeCount} | **Neutral:** ${neutralCount}`,
    "",
    "## Lessons Learned",
    "",
    "| # | Category | Impact | Description | Recommendation |",
    "|---|----------|--------|-------------|----------------|",
  ];

  params.lessonsLearned.forEach((lesson, i) => {
    const impactEmoji =
      lesson.impact === "positive" ? "✅" :
      lesson.impact === "negative" ? "❌" : "➡️";
    lines.push(
      `| ${i + 1} | ${lesson.category} | ${impactEmoji} ${lesson.impact} | ${lesson.description} | ${lesson.recommendation} |`
    );
  });

  lines.push(
    "",
    "## Action Items for Future Projects",
    "| # | Recommendation | Owner | Target |",
    "|---|----------------|-------|--------|",
    ...params.lessonsLearned
      .filter((l) => l.impact === "negative")
      .map((l, i) => `| ${i + 1} | ${l.recommendation} | _PMO_ | Next project kickoff |`),
    "",
    "---",
    "_Generated by Lliam PM Documents — PMI PMBOK-Aligned_"
  );

  return lines.join("\n");
}

function buildChangeRequest(params: {
  projectName: string;
  requestedBy: string;
  changeDescription: string;
  justification: string;
  impact: {
    scope?: string;
    schedule?: string;
    cost?: string;
    quality?: string;
  };
  priority: string;
}): string {
  const date = timestamp();
  const crId = `CR-${Date.now().toString().slice(-6)}`;

  const lines: string[] = [
    headerBlock("Change Request", params.projectName, date),
    `**Change Request ID:** ${crId}`,
    `**Priority:** ${params.priority.toUpperCase()}`,
    `**Requested By:** ${params.requestedBy}`,
    `**Status:** Submitted — Pending CCB Review`,
    "",
    "## Change Description",
    params.changeDescription,
    "",
    "## Justification / Business Case",
    params.justification,
    "",
    "## Impact Assessment",
    "| Dimension | Impact |",
    "|-----------|--------|",
    `| Scope | ${params.impact.scope ?? "No impact"} |`,
    `| Schedule | ${params.impact.schedule ?? "No impact"} |`,
    `| Cost | ${params.impact.cost ?? "No impact"} |`,
    `| Quality | ${params.impact.quality ?? "No impact"} |`,
    "",
    "## Change Control Board Decision",
    "| Decision | ☐ Approved  ☐ Rejected  ☐ Deferred |",
    "|----------|--------------------------------------|",
    "| Rationale | |",
    "| Decision By | |",
    "| Decision Date | |",
    "",
    "## Implementation Plan",
    "_To be completed upon CCB approval._",
    "",
    "---",
    "_Generated by Lliam PM Documents — PMI PMBOK-Aligned_",
  ];

  return lines.join("\n");
}

// ─── Plugin Definition ────────────────────────────────────────────────────────

const pmDocumentsPlugin: PluginModule = {
  id: "executive.pm-documents",
  name: "PM Documents",
  version: "1.0.0",
  description: "Generate PMI-aligned PM artifacts: charters, risk registers, RACI, status reports, and more",

  register(api: PluginAPI): void {
    const config = api.pluginConfig as {
      outputPath?: string;
      defaultFormat?: string;
    };

    const outputPath = resolve(api.resolvePath(config.outputPath ?? "./pm-artifacts"));

    // ─── generate_project_charter ────────────────────────────────

    api.registerTool({
      name: "generate_project_charter",
      description:
        "Generate a PMI-aligned Project Charter. The charter formally authorizes the project " +
        "and establishes the Project Manager's authority. Output is structured Markdown saved " +
        "to the configured artifacts directory.",
      parameters: {
        type: "object" as const,
        properties: {
          projectName: { type: "string", description: "Project name" },
          sponsor: { type: "string", description: "Project sponsor name and/or title" },
          objectives: {
            type: "array",
            items: { type: "string" },
            description: "List of measurable project objectives (SMART format recommended)",
          },
          scope: { type: "string", description: "High-level scope statement" },
          budget: { type: "string", description: "Budget authorization (optional)" },
          timeline: { type: "string", description: "High-level timeline or key milestones (optional)" },
          stakeholders: {
            type: "array",
            items: { type: "string" },
            description: "List of key stakeholder names/roles (optional)",
          },
        },
        required: ["projectName", "sponsor", "objectives", "scope"],
      },
      async execute(_toolCallId: string, params: Record<string, unknown>) {
        const content = buildProjectCharter({
          projectName: String(params["projectName"]),
          sponsor: String(params["sponsor"]),
          objectives: (params["objectives"] as string[]) ?? [],
          scope: String(params["scope"]),
          budget: params["budget"] ? String(params["budget"]) : undefined,
          timeline: params["timeline"] ? String(params["timeline"]) : undefined,
          stakeholders: params["stakeholders"] as string[] | undefined,
        });

        const fileName = `${String(params["projectName"]).replace(/\s+/g, "-")}-charter.md`;
        const savedPath = saveArtifact(outputPath, fileName, content);

        return { content: `${content}\n\n---\n_Saved to: ${savedPath}_` };
      },
    });

    // ─── generate_risk_register ──────────────────────────────────

    api.registerTool({
      name: "generate_risk_register",
      description:
        "Generate a PMI-aligned Risk Register from a list of identified risks. " +
        "Creates a formatted register with ID, category, probability/impact columns, " +
        "and placeholder fields for owner and response strategy.",
      parameters: {
        type: "object" as const,
        properties: {
          projectName: { type: "string", description: "Project name" },
          risks: {
            type: "array",
            items: {
              type: "object",
              properties: {
                description: { type: "string" },
                category: { type: "string" },
                probability: { type: "string" },
                impact: { type: "string" },
              },
              required: ["description", "category", "probability", "impact"],
            },
            description: "Array of risk entries",
          },
        },
        required: ["projectName", "risks"],
      },
      async execute(_toolCallId: string, params: Record<string, unknown>) {
        const content = buildRiskRegister({
          projectName: String(params["projectName"]),
          risks: params["risks"] as Array<{
            description: string;
            category: string;
            probability: string;
            impact: string;
          }>,
        });

        const fileName = `${String(params["projectName"]).replace(/\s+/g, "-")}-risk-register.md`;
        const savedPath = saveArtifact(outputPath, fileName, content);

        return { content: `${content}\n\n---\n_Saved to: ${savedPath}_` };
      },
    });

    // ─── generate_raci_matrix ────────────────────────────────────

    api.registerTool({
      name: "generate_raci_matrix",
      description:
        "Generate a RACI (Responsible, Accountable, Consulted, Informed) matrix for a project. " +
        "Maps work packages to roles with clear accountability assignments.",
      parameters: {
        type: "object" as const,
        properties: {
          projectName: { type: "string", description: "Project name" },
          workPackages: {
            type: "array",
            items: { type: "string" },
            description: "List of work packages or deliverables",
          },
          roles: {
            type: "array",
            items: { type: "string" },
            description: "List of roles or stakeholder groups",
          },
          assignments: {
            type: "object",
            description: "Nested object: assignments[workPackage][role] = 'R'|'A'|'C'|'I'|''",
          },
        },
        required: ["projectName", "workPackages", "roles", "assignments"],
      },
      async execute(_toolCallId: string, params: Record<string, unknown>) {
        const content = buildRaciMatrix({
          projectName: String(params["projectName"]),
          workPackages: params["workPackages"] as string[],
          roles: params["roles"] as string[],
          assignments: params["assignments"] as Record<string, Record<string, string>>,
        });

        const fileName = `${String(params["projectName"]).replace(/\s+/g, "-")}-raci.md`;
        const savedPath = saveArtifact(outputPath, fileName, content);

        return { content: `${content}\n\n---\n_Saved to: ${savedPath}_` };
      },
    });

    // ─── generate_stakeholder_engagement_plan ────────────────────

    api.registerTool({
      name: "generate_stakeholder_engagement_plan",
      description:
        "Generate a PMI-aligned Stakeholder Engagement Plan. Maps stakeholders to engagement " +
        "levels (Unaware → Leading), interests, and tailored engagement strategies.",
      parameters: {
        type: "object" as const,
        properties: {
          projectName: { type: "string", description: "Project name" },
          stakeholders: {
            type: "array",
            items: {
              type: "object",
              properties: {
                name: { type: "string" },
                role: { type: "string" },
                engagementLevel: { type: "string" },
                interests: { type: "string" },
                strategy: { type: "string" },
              },
              required: ["name", "role", "engagementLevel", "interests", "strategy"],
            },
            description: "Array of stakeholder entries",
          },
        },
        required: ["projectName", "stakeholders"],
      },
      async execute(_toolCallId: string, params: Record<string, unknown>) {
        const content = buildStakeholderEngagementPlan({
          projectName: String(params["projectName"]),
          stakeholders: params["stakeholders"] as Array<{
            name: string;
            role: string;
            engagementLevel: string;
            interests: string;
            strategy: string;
          }>,
        });

        const fileName = `${String(params["projectName"]).replace(/\s+/g, "-")}-stakeholder-plan.md`;
        const savedPath = saveArtifact(outputPath, fileName, content);

        return { content: `${content}\n\n---\n_Saved to: ${savedPath}_` };
      },
    });

    // ─── generate_status_report ──────────────────────────────────

    api.registerTool({
      name: "generate_status_report",
      description:
        "Generate a PMI-aligned project status report with RAG (Red/Amber/Green) health " +
        "indicators, accomplishments, planned work, issues, and active risks.",
      parameters: {
        type: "object" as const,
        properties: {
          projectName: { type: "string", description: "Project name" },
          reportingPeriod: { type: "string", description: "Reporting period (e.g. 'Week of 2025-04-07')" },
          accomplishments: {
            type: "array",
            items: { type: "string" },
            description: "Accomplishments this reporting period",
          },
          plannedWork: {
            type: "array",
            items: { type: "string" },
            description: "Work planned for next reporting period",
          },
          issues: {
            type: "array",
            items: { type: "string" },
            description: "Active issues requiring attention",
          },
          risks: {
            type: "array",
            items: { type: "string" },
            description: "Active risks (descriptions)",
          },
          scheduleVariance: {
            type: "string",
            description: "Schedule variance (e.g. '+2 days', '-5 days') (optional)",
          },
          budgetVariance: {
            type: "string",
            description: "Budget variance (e.g. '+$5,000 under', '-$10,000 over') (optional)",
          },
        },
        required: ["projectName", "reportingPeriod", "accomplishments", "plannedWork", "issues", "risks"],
      },
      async execute(_toolCallId: string, params: Record<string, unknown>) {
        const content = buildStatusReport({
          projectName: String(params["projectName"]),
          reportingPeriod: String(params["reportingPeriod"]),
          accomplishments: params["accomplishments"] as string[],
          plannedWork: params["plannedWork"] as string[],
          issues: params["issues"] as string[],
          risks: params["risks"] as string[],
          scheduleVariance: params["scheduleVariance"] ? String(params["scheduleVariance"]) : undefined,
          budgetVariance: params["budgetVariance"] ? String(params["budgetVariance"]) : undefined,
        });

        const fileName = `${String(params["projectName"]).replace(/\s+/g, "-")}-status-report.md`;
        const savedPath = saveArtifact(outputPath, fileName, content);

        return { content: `${content}\n\n---\n_Saved to: ${savedPath}_` };
      },
    });

    // ─── generate_wbs_dictionary ─────────────────────────────────

    api.registerTool({
      name: "generate_wbs_dictionary",
      description:
        "Generate a WBS Dictionary documenting each work package with description, " +
        "deliverables, acceptance criteria, and responsible party.",
      parameters: {
        type: "object" as const,
        properties: {
          projectName: { type: "string", description: "Project name" },
          workPackages: {
            type: "array",
            items: {
              type: "object",
              properties: {
                id: { type: "string" },
                name: { type: "string" },
                description: { type: "string" },
                deliverables: { type: "array", items: { type: "string" } },
                acceptanceCriteria: { type: "array", items: { type: "string" } },
                responsibleParty: { type: "string" },
              },
              required: ["id", "name", "description", "deliverables", "acceptanceCriteria", "responsibleParty"],
            },
            description: "Array of work package definitions",
          },
        },
        required: ["projectName", "workPackages"],
      },
      async execute(_toolCallId: string, params: Record<string, unknown>) {
        const content = buildWbsDictionary({
          projectName: String(params["projectName"]),
          workPackages: params["workPackages"] as Array<{
            id: string;
            name: string;
            description: string;
            deliverables: string[];
            acceptanceCriteria: string[];
            responsibleParty: string;
          }>,
        });

        const fileName = `${String(params["projectName"]).replace(/\s+/g, "-")}-wbs-dictionary.md`;
        const savedPath = saveArtifact(outputPath, fileName, content);

        return { content: `${content}\n\n---\n_Saved to: ${savedPath}_` };
      },
    });

    // ─── generate_lessons_learned ────────────────────────────────

    api.registerTool({
      name: "generate_lessons_learned",
      description:
        "Generate a Lessons Learned Register for a project phase. Categorizes lessons " +
        "by impact (positive/negative/neutral) and generates action items for future projects.",
      parameters: {
        type: "object" as const,
        properties: {
          projectName: { type: "string", description: "Project name" },
          phase: { type: "string", description: "Project phase (e.g. 'Planning', 'Executing', 'Closeout')" },
          lessonsLearned: {
            type: "array",
            items: {
              type: "object",
              properties: {
                category: { type: "string" },
                description: { type: "string" },
                recommendation: { type: "string" },
                impact: { type: "string", enum: ["positive", "negative", "neutral"] },
              },
              required: ["category", "description", "recommendation", "impact"],
            },
            description: "Array of lessons learned entries",
          },
        },
        required: ["projectName", "phase", "lessonsLearned"],
      },
      async execute(_toolCallId: string, params: Record<string, unknown>) {
        const content = buildLessonsLearned({
          projectName: String(params["projectName"]),
          phase: String(params["phase"]),
          lessonsLearned: params["lessonsLearned"] as Array<{
            category: string;
            description: string;
            recommendation: string;
            impact: string;
          }>,
        });

        const fileName = `${String(params["projectName"]).replace(/\s+/g, "-")}-lessons-learned.md`;
        const savedPath = saveArtifact(outputPath, fileName, content);

        return { content: `${content}\n\n---\n_Saved to: ${savedPath}_` };
      },
    });

    // ─── generate_change_request ─────────────────────────────────

    api.registerTool({
      name: "generate_change_request",
      description:
        "Generate a formal Change Request document for CCB (Change Control Board) review. " +
        "Includes impact assessment across scope, schedule, cost, and quality dimensions.",
      parameters: {
        type: "object" as const,
        properties: {
          projectName: { type: "string", description: "Project name" },
          requestedBy: { type: "string", description: "Name and role of change requestor" },
          changeDescription: { type: "string", description: "Clear description of the proposed change" },
          justification: { type: "string", description: "Business justification for the change" },
          impact: {
            type: "object",
            properties: {
              scope: { type: "string" },
              schedule: { type: "string" },
              cost: { type: "string" },
              quality: { type: "string" },
            },
            description: "Impact on scope, schedule, cost, and quality (all optional)",
          },
          priority: {
            type: "string",
            enum: ["low", "medium", "high", "critical"],
            description: "Change priority",
          },
        },
        required: ["projectName", "requestedBy", "changeDescription", "justification", "impact", "priority"],
      },
      async execute(_toolCallId: string, params: Record<string, unknown>) {
        const content = buildChangeRequest({
          projectName: String(params["projectName"]),
          requestedBy: String(params["requestedBy"]),
          changeDescription: String(params["changeDescription"]),
          justification: String(params["justification"]),
          impact: params["impact"] as { scope?: string; schedule?: string; cost?: string; quality?: string },
          priority: String(params["priority"]),
        });

        const fileName = `${String(params["projectName"]).replace(/\s+/g, "-")}-change-request.md`;
        const savedPath = saveArtifact(outputPath, fileName, content);

        return { content: `${content}\n\n---\n_Saved to: ${savedPath}_` };
      },
    });

    api.logger.info(`PM Documents plugin registered — artifacts → ${outputPath}`);
  },
};

export default pmDocumentsPlugin;
